### PR TITLE
alias: repl/reloaded-debug add sayid to reloaded workflow

### PR DESCRIPTION
**Pull request by allentiak**
📓 Description

A catch-all to have debugging, refactoring and hot reload.
Includes documentation.

### CODE REVIEW

**Comment by practicalli-john** [comment]
Suggest using the alias name `:repl/reloaded-debug`

**Comment by allentiak** [comment]
Thanks! I'll try it!

John Practicalli ***@***.***> schrieb am Mi., 23. Aug. 2023,
15:55:

**Comment by practicalli-john** [comment]
Adding this alias would define 3 aliases that include sayid and ideally I'd like to keep aliases to a minimum, especially as I do not use sayid and therefore unsure how to test it.

Which of the following aliases is the most useful to you?

```clojure
  :repl/rebel-debug
  {:extra-deps {nrepl/nrepl                {:mvn/version "1.0.0"}
                cider/cider-nrepl          {:mvn/version "0.31.0"}
                com.billpiel/sayid         {:mvn/version "0.1.0"}
                com.bhauman/rebel-readline {:mvn/version "0.1.4"}}
   :main-opts  ["-e" "(apply require clojure.main/repl-requires)"
                "--main" "nrepl.cmdline"
                "--middleware" "[com.billpiel.sayid.nrepl-middleware/wrap-sayid,cider.nrepl/cider-middleware]"
                "--interactive"
                "-f" "rebel-readline.main/-main"]}

  :repl/rebel-debug-refactor
  {:extra-deps {nrepl/nrepl                   {:mvn/version "1.0.0"}
                cider/cider-nrepl             {:mvn/version "0.31.0"}
                refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}
                com.billpiel/sayid            {:mvn/version "0.1.0"}
                com.bhauman/rebel-readline    {:mvn/version "0.1.4"}}
   :main-opts  ["-e" "(apply require clojure.main/repl-requires)"
                "--main" "nrepl.cmdline"
                "--middleware" "[com.billpiel.sayid.nrepl-middleware/wrap-sayid,refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"
                "--interactive"
                "-f" "rebel-readline.main/-main"]}

  :repl/reloaded-debug
  {:extra-paths ["dev" "test"]
   :extra-deps {nrepl/nrepl                  {:mvn/version "1.0.0"}
                cider/cider-nrepl            {:mvn/version "0.31.0"}
                com.bhauman/rebel-readline   {:mvn/version "0.1.4"}
                com.billpiel/sayid           {:mvn/version "0.1.0"}
                djblue/portal                {:mvn/version "0.42.1"}   ; portal data inspector
                clj-commons/clj-yaml         {:mvn/version "1.0.26"}   ; portal yaml support (optional)
                org.clojure/tools.namespace  {:mvn/version "1.4.4"}
                org.clojure/tools.trace      {:mvn/version "0.7.11"}
                org.slf4j/slf4j-nop          {:mvn/version "2.0.7"}
                com.brunobonacci/mulog       {:mvn/version "0.9.0"}
                lambdaisland/kaocha          {:mvn/version "1.85.1342"}
                org.clojure/test.check       {:mvn/version "1.1.1"}
                refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}
                ring/ring-mock               {:mvn/version "0.4.0"}
                criterium/criterium          {:mvn/version "0.4.6"}}
   :main-opts  ["-e" "(apply require clojure.main/repl-requires)"
                "--main" "nrepl.cmdline"
                "--middleware" "[cider.nrepl/cider-middleware,refactor-nrepl.middleware/wrap-refactor,com.billpiel.sayid.nrepl-middleware/wrap-sayid,portal.nrepl/wrap-portal]"
                "--interactive"
                "-f" "rebel-readline.main/-main"]}
```

I'm also considering deprecating the following aliases and replacing them with what ever rebel versions are actually of use.

```clojure
  :repl/refactor
  {:extra-deps {nrepl/nrepl                   {:mvn/version "1.0.0"}
                cider/cider-nrepl             {:mvn/version "0.31.0"}
                refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}}
   :main-opts  ["--main" "nrepl.cmdline"
                "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"
                "--interactive"]}

  :repl/debug
  {:extra-deps {nrepl/nrepl        {:mvn/version "1.0.0"}
                com.billpiel/sayid {:mvn/version "0.1.0"}
                cider/cider-nrepl  {:mvn/version "0.31.0"}}
   :main-opts  ["--main" "nrepl.cmdline"
                "--middleware" "[com.billpiel.sayid.nrepl-middleware/wrap-sayid,cider.nrepl/cider-middleware]"
                "--interactive"]}

  :repl/debug-refactor
  {:extra-deps {nrepl/nrepl                   {:mvn/version "1.0.0"}
                cider/cider-nrepl             {:mvn/version "0.31.0"}
                refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}
                com.billpiel/sayid            {:mvn/version "0.1.0"}}
   :main-opts  ["--main" "nrepl.cmdline"
                "--middleware" "[com.billpiel.sayid.nrepl-middleware/wrap-sayid,refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"
                "--interactive"]}
```

**Comment by allentiak** [comment]
I'm sorry for my late reply.
I currently do not have the time for testing this.
I will get back to this as soon as I do.

**Pull request closed without merging**
